### ISSUE TITLE
how to change mode between live and backtest

### ISSUE THREAD

**Issue by SenYoung** [btrccts/btrccts#153]
how to change mode between live and backtest, are there some examples between two modes code difference, thanks

**Comment by brandsimon** [comment]
If you created the exchange like described here [0], you can use the parameter `--live`.
The documentation about it is missing, I will add it this week.
Does this answer your question?

[0] https://github.com/btrccts/btrccts/blob/main/examples/algo_readme.py#L24

**Comment by brandsimon** [comment]
I fixed it in 4e66b42
